# site configuration
title: Example website
author: Paragoo
description: Default description of this website
copyright: Copyleft Paragoo Labs
footer: Copyleft Paragoo Labs
subdirs: true
sections:
    section_1:
        title: Section 1
        pages:
            page-1:
                title: Page number 1
                # filename is implicit: page-1.md and page-1.html will be tried
            nonexisting:
                title: Should not be there
    section_2:
        title: Section numero dos
        pages:
            42-you-know:
                title: 42 you know
            info:
                title: Info page
            pics:
                title: Pictures
                type: gallery
